---
title: "MLB Pitcher Performance Runners On vs Not On"
author: "Riley Feltner"
date: "11/5/2022"
output: html_document
---

```{r}
NoRunnersOn <- read.csv("2022 SP No Runners On.csv")
RunnersOn <- read.csv("2022 SP Runners On.csv")

newdata <- merge(NoRunnersOn, RunnersOn, by = "player_id")
#x is no runners on, y is runners on
```

#xBA Difference between x(no runners on) and y(runner on)
```{r}
library(dplyr)
newdata <- mutate(newdata, xbadifference = xba.x - xba.y)

#make xbadifference more viewable
Filtereddata <- newdata[,c(1, 3, 2, 12, 32, 42, 62)]
Filtereddata1<- filter(Filtereddata, pitches.x > 500 & pitches.y >500)

```

#Order
```{r}
Top10 <- arrange(Filtereddata1, xbadifference) %>% tail(10)
Top10[(order(Top10$xbadifference)),]
```

```{r}
library(devtools)
#devtools::install_github("camdenk/mlbplotR")
```

```{r}
library(devtools)
#devtools::install_github("camdenk/mlbplotR")
library(ggplot2)
Top10 %>%
    ggplot(aes(x=xba.x, y=10:1)) +
    mlbplotR::geom_mlb_headshots(aes(player_id = player_id, x 
    = xba.x + 0.006), height = 0.12)+
    geom_point(colour = "black") + 
    geom_segment( aes(x=xba.y, xend=xba.x, y= 10:1, yend 
    =10:1))+
    theme_classic()+
    geom_point(aes(x=xba.x, y=10:1))+
    geom_point(aes(x=xba.y, y=10:1))+
    geom_text(aes(label = xbadifference), size = 2, hjust = -2, vjust = .55)+
    geom_text(aes(label= player_name.x), size = 2, hjust = 1, vjust = -.70)+
    labs(title = "MLB 2022 Top 10 xBA Decrease with Runners On vs Bases Empty",
         subtitle = "SP with 500 + Pitches with Runners On and Bases Empty",
     y = "xBA Difference Rank",
     x = "xBA",
     caption = "Data: Baseball Savant | Riley Feltner || Logos: mlbplotR")

```








